<a href="https://colab.research.google.com/github/efesefe/BugFinder_Machine_Learning/blob/main/Bug_Finder_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [426]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import glob
import os
from sklearn.model_selection import cross_val_score

In [427]:
allData = pd.concat(map(pd.read_csv, glob.glob(os.path.join('', "*.csv"))))
allData.drop('name.1', axis=1, inplace=True)
allData.drop('version', axis=1, inplace=True)

In [428]:
X = allData.iloc[:, :-1].values
y = allData.iloc[:, -1].values
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = pd.DataFrame(ct.fit_transform(X))
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X = pd.DataFrame(scaler.transform(X))

In [429]:
from sklearn.neighbors import LocalOutlierFactor
clf = LocalOutlierFactor(n_neighbors = 20, contamination = 0.1)
clf.fit_predict(X)
df_scores = clf.negative_outlier_factor_
esik_deger = np.sort(df_scores)[13]
aykiri_tf = df_scores > esik_deger
baski_deger =  X[df_scores == esik_deger]
aykirilar = X[~aykiri_tf]
aykirilar.to_records(index = False)
res = aykirilar.to_records(index = False)
res[:] = baski_deger.to_records(index = False)
X[~aykiri_tf] = pd.DataFrame(res, index = X[~aykiri_tf].index)
y[y > 0] = 1
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

###İBRAHİM EFE ERER

In [430]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)
rfc_pred = rfc.predict(X_test)
print(accuracy_score(y_test, rfc_pred))
print(confusion_matrix(y_test, rfc_pred))
print("10-Fold Cross validation score")
print(cross_val_score(rfc,X,y,cv=10,scoring='accuracy').mean())

0.8602383531960996
[[545  37]
 [ 92 249]]
10-Fold Cross validation score
0.7296588444093868


In [431]:
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import SVC
clf = BaggingClassifier(base_estimator=SVC(), n_estimators=10, random_state=0).fit(X_train, y_train)
bagging_result = clf.predict(X_test)
print(accuracy_score(y_test, bagging_result))
print(confusion_matrix(y_test, bagging_result))
print("10-Fold Cross validation score")
print(cross_val_score(clf,X,y,cv=10,scoring='accuracy').mean())

0.8266522210184182
[[545  37]
 [123 218]]
10-Fold Cross validation score
0.6932637499882619


In [432]:
from sklearn.linear_model import LogisticRegression
clf_logistic = LogisticRegression(random_state=0).fit(X_train, y_train)
logistic_pred = clf_logistic.predict(X_test)

print(accuracy_score(y_test, logistic_pred))
print(confusion_matrix(y_test, logistic_pred))
print("10-Fold Cross validation score")
print(cross_val_score(clf_logistic,X,y,cv=10,scoring='accuracy').mean())

0.8223185265438786
[[515  67]
 [ 97 244]]
10-Fold Cross validation score
0.6963184682273619


###CAN ATEŞ:

In [433]:
from sklearn.naive_bayes import GaussianNB

bayes = GaussianNB()
bayes.fit(X_train , y_train)

y_pred = bayes.predict(X_test)

print(accuracy_score(y_test,y_pred))

print("10-Fold Cross validation score")
print(cross_val_score(bayes,X,y,cv=10,scoring='accuracy').mean())

0.8179848320693391
10-Fold Cross validation score
0.6513991792733659


In [434]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=15)
knn.fit(X_train, y_train)
pred = knn.predict(X_test)
print(accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred))
print("10-Fold Cross validation score")
print(cross_val_score(knn,X,y,cv=10,scoring='accuracy').mean())

0.8277356446370531
[[532  50]
 [109 232]]
10-Fold Cross validation score
0.6919580058408692


##YAZGI KAVUKÇU

In [435]:
from sklearn.tree import DecisionTreeClassifier
regr = DecisionTreeClassifier()
regr.fit(X_train, y_train)
result = regr.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, result))
print(confusion_matrix(y_test, result))
print("10-Fold Cross validation score")
print(cross_val_score(regr,X,y,cv=10,scoring='accuracy').mean())

0.8071505958829902
[[499  83]
 [ 95 246]]
10-Fold Cross validation score
0.6900207529274776


In [436]:
from sklearn.svm import SVC

svc = SVC()

svc.fit(X_train , y_train)

y_pred = svc.predict(X_test)

print(accuracy_score(y_test,y_pred))

print("10-Fold Cross validation score")
print(cross_val_score(svc,X,y,cv=10,scoring='accuracy').mean())

0.8320693391115926
10-Fold Cross validation score
0.6941318984702933
